"""Repo-style lint rules not covered by ruff or other off-the-shelf tools.

Each rule is a function taking `(path, source)` and yielding `Violation`
records, defined in a themed module. This package re-exports the whole
public surface, so `from repostyle.rules import <name>` resolves
regardless of which module the name lives in.
"""

from __future__ import annotations

from repostyle.rules._catalog import (
    ABBREVIATION_EXPANSIONS,
    RULE_DOCS,
    Example,
    RuleDoc,
    has_guidance,
    rule_doc,
)
from repostyle.rules._registry import (
    ALL_RULE_IDS,
    FIXABLE_RULES,
    PACKAGE_RULES,
    RULE_SEVERITY,
    RULES,
    run_package_rule,
    run_rule,
    severity_of,
)
from repostyle.rules._violation import (
    RS_ACRONYM_CASING,
    RS_ARG_DESCRIBED_IN_PROSE,
    RS_BANNED_ABBREVIATION,
    RS_BANNED_IMPORT_BY_PATH,
    RS_BEHAVIOR_VERIFICATION_ONLY,
    RS_BOOLEAN_PREFIX_REQUIRED,
    RS_COGNITIVE_COMPLEXITY,
    RS_COMMENT_TAG_FORMAT,
    RS_CONDITIONAL_TEST_LOGIC,
    RS_DISCOURAGED_CLASS_SUFFIX,
    RS_DOC_FILL,
    RS_DOC_VALUE_SIGNAL,
    RS_DURATION_AS_TIMEDELTA,
    RS_ELEMENT_ORDER,
    RS_EXCEPTION_ALIAS,
    RS_EXCESSIVE_MOCKING,
    RS_FIELD_COMMENT_AS_DOCSTRING,
    RS_FILLER_DOCSTRING_OPENING,
    RS_NO_ATTRIBUTES_BLOCK,
    RS_NO_DOUBLE_BACKTICKS,
    RS_NO_MAKE_IN_PRODUCTION,
    RS_NO_MOCK_PATCH,
    RS_NO_NEGATED_BOOLEAN,
    RS_NO_PHI_SAFE_EXC_INFO,
    RS_PORT_NO_IMPLEMENTATION,
    RS_SHOULD_BE_PRIVATE,
    RS_SLEEPY_TEST,
    RS_SUMMARY_COMMENT_AS_DOCSTRING,
    RS_TERMINAL_PUNCTUATION,
    RS_TEST_NAMING,
    RS_TOO_MANY_POSITIONAL_ARGS,
    Severity,
    Violation,
)
from repostyle.rules.comments import (
    check_comment_tag_format,
    check_comment_terminal_punctuation,
    fix_comment_terminal_punctuation,
)
from repostyle.rules.complexity import check_cognitive_complexity
from repostyle.rules.doc_fill import DOC_FILL_COLUMNS, check_doc_fill, reflow_doc_fill
from repostyle.rules.doc_value import (
    check_arg_described_in_prose,
    check_doc_value_signal,
)
from repostyle.rules.docstrings import (
    check_docstring_terminal_punctuation,
    check_field_comment_as_docstring,
    check_filler_docstring_opening,
    check_no_attributes_block,
    check_no_double_backticks_in_docstrings,
    check_no_double_backticks_in_md,
    check_summary_comment_as_docstring,
    fix_docstring_terminal_punctuation,
    fix_double_backticks,
)
from repostyle.rules.duration import check_duration_as_timedelta
from repostyle.rules.import_layering import check_banned_import_by_path
from repostyle.rules.layout import (
    check_class_member_order,
    check_module_element_order,
)
from repostyle.rules.logging_phi import check_no_phi_safe_with_exc_info
from repostyle.rules.naming import (
    check_acronym_casing,
    check_banned_abbreviation,
    check_boolean_prefix_required,
    check_discouraged_class_suffix,
    check_exception_alias,
    check_no_make_in_production,
    check_no_negated_boolean,
)
from repostyle.rules.ports import check_port_no_implementation
from repostyle.rules.signatures import check_too_many_positional_args
from repostyle.rules.testing import (
    check_behavior_verification_only,
    check_conditional_test_logic,
    check_excessive_mocking,
    check_no_mock_patch,
    check_sleepy_test,
    check_test_naming,
)
from repostyle.rules.visibility import check_should_be_private

__all__ = [
    "ABBREVIATION_EXPANSIONS",
    "ALL_RULE_IDS",
    "DOC_FILL_COLUMNS",
    "FIXABLE_RULES",
    "PACKAGE_RULES",
    "RULES",
    "RULE_DOCS",
    "RULE_SEVERITY",
    "RS_ACRONYM_CASING",
    "RS_ARG_DESCRIBED_IN_PROSE",
    "RS_BANNED_ABBREVIATION",
    "RS_BANNED_IMPORT_BY_PATH",
    "RS_BEHAVIOR_VERIFICATION_ONLY",
    "RS_BOOLEAN_PREFIX_REQUIRED",
    "RS_COGNITIVE_COMPLEXITY",
    "RS_COMMENT_TAG_FORMAT",
    "RS_CONDITIONAL_TEST_LOGIC",
    "RS_DISCOURAGED_CLASS_SUFFIX",
    "RS_DOC_FILL",
    "RS_DOC_VALUE_SIGNAL",
    "RS_DURATION_AS_TIMEDELTA",
    "RS_ELEMENT_ORDER",
    "RS_EXCEPTION_ALIAS",
    "RS_EXCESSIVE_MOCKING",
    "RS_FIELD_COMMENT_AS_DOCSTRING",
    "RS_FILLER_DOCSTRING_OPENING",
    "RS_NO_ATTRIBUTES_BLOCK",
    "RS_NO_DOUBLE_BACKTICKS",
    "RS_NO_MAKE_IN_PRODUCTION",
    "RS_NO_MOCK_PATCH",
    "RS_NO_NEGATED_BOOLEAN",
    "RS_NO_PHI_SAFE_EXC_INFO",
    "RS_PORT_NO_IMPLEMENTATION",
    "RS_SHOULD_BE_PRIVATE",
    "RS_SLEEPY_TEST",
    "RS_SUMMARY_COMMENT_AS_DOCSTRING",
    "RS_TERMINAL_PUNCTUATION",
    "RS_TEST_NAMING",
    "RS_TOO_MANY_POSITIONAL_ARGS",
    "Example",
    "RuleDoc",
    "Severity",
    "Violation",
    "check_acronym_casing",
    "check_arg_described_in_prose",
    "check_banned_abbreviation",
    "check_banned_import_by_path",
    "check_behavior_verification_only",
    "check_boolean_prefix_required",
    "check_class_member_order",
    "check_cognitive_complexity",
    "check_comment_tag_format",
    "check_comment_terminal_punctuation",
    "check_conditional_test_logic",
    "check_discouraged_class_suffix",
    "check_doc_fill",
    "check_doc_value_signal",
    "check_docstring_terminal_punctuation",
    "check_duration_as_timedelta",
    "check_exception_alias",
    "check_excessive_mocking",
    "check_field_comment_as_docstring",
    "check_filler_docstring_opening",
    "check_module_element_order",
    "check_no_attributes_block",
    "check_no_double_backticks_in_docstrings",
    "check_no_double_backticks_in_md",
    "check_no_make_in_production",
    "check_no_mock_patch",
    "check_no_negated_boolean",
    "check_no_phi_safe_with_exc_info",
    "check_port_no_implementation",
    "check_should_be_private",
    "check_sleepy_test",
    "check_summary_comment_as_docstring",
    "check_test_naming",
    "check_too_many_positional_args",
    "fix_comment_terminal_punctuation",
    "fix_docstring_terminal_punctuation",
    "fix_double_backticks",
    "has_guidance",
    "reflow_doc_fill",
    "rule_doc",
    "run_package_rule",
    "run_rule",
    "severity_of",
]
