"""Repo-style lint rules not covered by ruff or other off-the-shelf tools.

Each rule is a function taking `(path, source)` and yielding `Violation`
records, defined in a themed module. This package re-exports the whole public
surface, so `from repostyle.rules import <name>` resolves regardless of which
module the name lives in.
"""

from __future__ import annotations

from repostyle.rules._catalog import (
    ABBREVIATION_EXPANSIONS,
    RULE_DOCS,
    Example,
    RuleDoc,
    has_guidance,
    rule_doc,
)
from repostyle.rules._registry import (
    ALL_RULE_IDS,
    FIXABLE_RULES,
    PACKAGE_RULES,
    RULE_SEVERITY,
    RULES,
    run_package_rule,
    run_rule,
    severity_of,
)
from repostyle.rules._violation import (
    RS_ACRONYM_CASING,
    RS_ACRONYM_CASING_IN_PROSE,
    RS_ARG_DESCRIBED_IN_PROSE,
    RS_BANNED_ABBREVIATION,
    RS_BANNED_IMPORT_BY_PATH,
    RS_BEHAVIOR_VERIFICATION_ONLY,
    RS_BOOLEAN_PREFIX_REQUIRED,
    RS_COGNITIVE_COMPLEXITY,
    RS_COMMENT_TAG_FORMAT,
    RS_CONDITIONAL_TEST_LOGIC,
    RS_DEEPLY_NESTED_TYPE,
    RS_DISCOURAGED_CLASS_SUFFIX,
    RS_DISFAVORED_GCP_TERM,
    RS_DOC_FILL,
    RS_DOC_SUMMARY_OVERFLOW,
    RS_DOC_VALUE_SIGNAL,
    RS_DURATION_AS_TIMEDELTA,
    RS_ELEMENT_ORDER,
    RS_EQ_HASH_PAIRING,
    RS_EXCEPTION_ALIAS,
    RS_EXCESSIVE_MOCKING,
    RS_FIELD_COMMENT_AS_DOCSTRING,
    RS_FILENAME_CONVENTION,
    RS_FILLER_DOCSTRING_OPENING,
    RS_GLUED_CODE_SPAN,
    RS_IMPERATIVE_DOCSTRING_OPENING,
    RS_LOWERCASE_ENTRY_DESCRIPTION,
    RS_NO_ATTRIBUTES_BLOCK,
    RS_NO_DOUBLE_BACKTICKS,
    RS_NO_MAKE_IN_PRODUCTION,
    RS_NO_MOCK_PATCH,
    RS_NO_NEGATED_BOOLEAN,
    RS_NO_PHI_SAFE_EXC_INFO,
    RS_PORT_NO_IMPLEMENTATION,
    RS_PREDICATE_FUNCTION_NAMING,
    RS_PRIVATE_IMPORT,
    RS_RAISE_DESCRIBED_IN_PROSE,
    RS_RAISES_SECTION_INCOMPLETE,
    RS_RANGE_LEN_REINDEX,
    RS_RETURN_DESCRIBED_IN_PROSE,
    RS_SHOULD_BE_PRIVATE,
    RS_SLEEPY_TEST,
    RS_SUMMARY_COMMENT_AS_DOCSTRING,
    RS_TAG_COMMENT_CONTINUATION_INDENT,
    RS_TEMPORAL_MARKER,
    RS_TERMINAL_PUNCTUATION,
    RS_TEST_NAMING,
    RS_TOO_MANY_POSITIONAL_ARGS,
    RS_UNBACKTICKED_CODE_REFERENCE,
    RS_UNBACKTICKED_SIBLING_SYMBOL,
    Severity,
    Violation,
)
from repostyle.rules.annotations import check_deeply_nested_type
from repostyle.rules.comments import (
    check_acronym_casing_in_comments,
    check_comment_tag_format,
    check_comment_temporal_markers,
    check_comment_terminal_punctuation,
    check_gcp_product_name_in_comments,
    check_tag_comment_continuation_indent,
    fix_acronym_casing_in_comments,
    fix_comment_terminal_punctuation,
    fix_gcp_product_name_in_comments,
)
from repostyle.rules.complexity import check_cognitive_complexity
from repostyle.rules.doc_fill import (
    DOC_FILL_COLUMNS,
    check_doc_fill,
    check_doc_summary_overflow,
    fix_doc_fill,
)
from repostyle.rules.doc_value import (
    check_arg_described_in_prose,
    check_doc_value_signal,
    check_raise_described_in_prose,
    check_raises_section_incomplete,
    check_return_described_in_prose,
)
from repostyle.rules.docstrings import (
    check_acronym_casing_in_docstrings,
    check_docstring_temporal_markers,
    check_docstring_terminal_punctuation,
    check_field_comment_as_docstring,
    check_filler_docstring_opening,
    check_gcp_product_name_in_docstrings,
    check_glued_code_span_in_comments,
    check_glued_code_span_in_docstrings,
    check_glued_code_span_in_md,
    check_imperative_docstring_opening,
    check_lowercase_entry_description,
    check_no_attributes_block,
    check_no_double_backticks_in_docstrings,
    check_no_double_backticks_in_md,
    check_summary_comment_as_docstring,
    check_unbackticked_code_reference,
    check_unbackticked_sibling_symbol,
    check_unbackticked_sibling_symbol_in_comments,
    fix_acronym_casing_in_docstrings,
    fix_docstring_terminal_punctuation,
    fix_double_backticks,
    fix_gcp_product_name_in_docstrings,
)
from repostyle.rules.duration import check_duration_as_timedelta
from repostyle.rules.encapsulation import check_private_import
from repostyle.rules.equality import check_eq_hash_pairing
from repostyle.rules.filenames import check_filename_casing, check_filename_extension
from repostyle.rules.idioms import check_range_len_reindex
from repostyle.rules.import_layering import check_banned_import_by_path
from repostyle.rules.layout import (
    check_class_member_order,
    check_module_element_order,
)
from repostyle.rules.logging_phi import check_no_phi_safe_with_exc_info
from repostyle.rules.naming import (
    check_acronym_casing,
    check_banned_abbreviation,
    check_boolean_prefix_required,
    check_discouraged_class_suffix,
    check_exception_alias,
    check_no_make_in_production,
    check_no_negated_boolean,
    check_predicate_function_naming,
)
from repostyle.rules.ports import check_port_no_implementation
from repostyle.rules.signatures import check_too_many_positional_args
from repostyle.rules.testing import (
    check_behavior_verification_only,
    check_conditional_test_logic,
    check_excessive_mocking,
    check_no_mock_patch,
    check_sleepy_test,
    check_test_naming,
)
from repostyle.rules.visibility import check_should_be_private

__all__ = [
    "ABBREVIATION_EXPANSIONS",
    "ALL_RULE_IDS",
    "DOC_FILL_COLUMNS",
    "FIXABLE_RULES",
    "PACKAGE_RULES",
    "RS_ACRONYM_CASING",
    "RS_ACRONYM_CASING_IN_PROSE",
    "RS_ARG_DESCRIBED_IN_PROSE",
    "RS_BANNED_ABBREVIATION",
    "RS_BANNED_IMPORT_BY_PATH",
    "RS_BEHAVIOR_VERIFICATION_ONLY",
    "RS_BOOLEAN_PREFIX_REQUIRED",
    "RS_COGNITIVE_COMPLEXITY",
    "RS_COMMENT_TAG_FORMAT",
    "RS_CONDITIONAL_TEST_LOGIC",
    "RS_DEEPLY_NESTED_TYPE",
    "RS_DISCOURAGED_CLASS_SUFFIX",
    "RS_DISFAVORED_GCP_TERM",
    "RS_DOC_FILL",
    "RS_DOC_SUMMARY_OVERFLOW",
    "RS_DOC_VALUE_SIGNAL",
    "RS_DURATION_AS_TIMEDELTA",
    "RS_ELEMENT_ORDER",
    "RS_EQ_HASH_PAIRING",
    "RS_EXCEPTION_ALIAS",
    "RS_EXCESSIVE_MOCKING",
    "RS_FIELD_COMMENT_AS_DOCSTRING",
    "RS_FILENAME_CONVENTION",
    "RS_FILLER_DOCSTRING_OPENING",
    "RS_GLUED_CODE_SPAN",
    "RS_IMPERATIVE_DOCSTRING_OPENING",
    "RS_LOWERCASE_ENTRY_DESCRIPTION",
    "RS_NO_ATTRIBUTES_BLOCK",
    "RS_NO_DOUBLE_BACKTICKS",
    "RS_NO_MAKE_IN_PRODUCTION",
    "RS_NO_MOCK_PATCH",
    "RS_NO_NEGATED_BOOLEAN",
    "RS_NO_PHI_SAFE_EXC_INFO",
    "RS_PORT_NO_IMPLEMENTATION",
    "RS_PREDICATE_FUNCTION_NAMING",
    "RS_PRIVATE_IMPORT",
    "RS_RAISES_SECTION_INCOMPLETE",
    "RS_RAISE_DESCRIBED_IN_PROSE",
    "RS_RANGE_LEN_REINDEX",
    "RS_RETURN_DESCRIBED_IN_PROSE",
    "RS_SHOULD_BE_PRIVATE",
    "RS_SLEEPY_TEST",
    "RS_SUMMARY_COMMENT_AS_DOCSTRING",
    "RS_TAG_COMMENT_CONTINUATION_INDENT",
    "RS_TEMPORAL_MARKER",
    "RS_TERMINAL_PUNCTUATION",
    "RS_TEST_NAMING",
    "RS_TOO_MANY_POSITIONAL_ARGS",
    "RS_UNBACKTICKED_CODE_REFERENCE",
    "RS_UNBACKTICKED_SIBLING_SYMBOL",
    "RULES",
    "RULE_DOCS",
    "RULE_SEVERITY",
    "Example",
    "RuleDoc",
    "Severity",
    "Violation",
    "check_acronym_casing",
    "check_acronym_casing_in_comments",
    "check_acronym_casing_in_docstrings",
    "check_arg_described_in_prose",
    "check_banned_abbreviation",
    "check_banned_import_by_path",
    "check_behavior_verification_only",
    "check_boolean_prefix_required",
    "check_class_member_order",
    "check_cognitive_complexity",
    "check_comment_tag_format",
    "check_comment_temporal_markers",
    "check_comment_terminal_punctuation",
    "check_conditional_test_logic",
    "check_deeply_nested_type",
    "check_discouraged_class_suffix",
    "check_doc_fill",
    "check_doc_summary_overflow",
    "check_doc_value_signal",
    "check_docstring_temporal_markers",
    "check_docstring_terminal_punctuation",
    "check_duration_as_timedelta",
    "check_eq_hash_pairing",
    "check_exception_alias",
    "check_excessive_mocking",
    "check_field_comment_as_docstring",
    "check_filename_casing",
    "check_filename_extension",
    "check_filler_docstring_opening",
    "check_gcp_product_name_in_comments",
    "check_gcp_product_name_in_docstrings",
    "check_glued_code_span_in_comments",
    "check_glued_code_span_in_docstrings",
    "check_glued_code_span_in_md",
    "check_imperative_docstring_opening",
    "check_lowercase_entry_description",
    "check_module_element_order",
    "check_no_attributes_block",
    "check_no_double_backticks_in_docstrings",
    "check_no_double_backticks_in_md",
    "check_no_make_in_production",
    "check_no_mock_patch",
    "check_no_negated_boolean",
    "check_no_phi_safe_with_exc_info",
    "check_port_no_implementation",
    "check_predicate_function_naming",
    "check_private_import",
    "check_raise_described_in_prose",
    "check_raises_section_incomplete",
    "check_range_len_reindex",
    "check_return_described_in_prose",
    "check_should_be_private",
    "check_sleepy_test",
    "check_summary_comment_as_docstring",
    "check_tag_comment_continuation_indent",
    "check_test_naming",
    "check_too_many_positional_args",
    "check_unbackticked_code_reference",
    "check_unbackticked_sibling_symbol",
    "check_unbackticked_sibling_symbol_in_comments",
    "fix_acronym_casing_in_comments",
    "fix_acronym_casing_in_docstrings",
    "fix_comment_terminal_punctuation",
    "fix_doc_fill",
    "fix_docstring_terminal_punctuation",
    "fix_double_backticks",
    "fix_gcp_product_name_in_comments",
    "fix_gcp_product_name_in_docstrings",
    "has_guidance",
    "rule_doc",
    "run_package_rule",
    "run_rule",
    "severity_of",
]
