"""Binds checks for documentation rules."""

from repostyle.rules._violation import (
    RS_ACRONYM_CASING_IN_PROSE,
    RS_ARG_DESCRIBED_IN_PROSE,
    RS_BANNER_COMMENT,
    RS_BULLET_ITEM_CASING,
    RS_COMMENT_TAG_FORMAT,
    RS_DISFAVORED_GCP_TERM,
    RS_DOC_FILL,
    RS_DOC_SUMMARY_OVERFLOW,
    RS_DOC_VALUE_SIGNAL,
    RS_DOCSTRING_SECTION_ALIAS,
    RS_DOCSTRING_SECTION_ORDER,
    RS_DOUBLE_SPACE_AFTER_PERIOD,
    RS_DUPLICATE_DOCSTRING_SECTION,
    RS_FIELD_COMMENT_AS_DOCSTRING,
    RS_FIELD_DESCRIBED_IN_CLASS_DOCSTRING,
    RS_FILLER_DOCSTRING_OPENING,
    RS_GLUED_CODE_SPAN,
    RS_INLINE_NUMBERED_LIST,
    RS_INVALID_DOCSTRING_SECTION,
    RS_LOWERCASE_ENTRY_DESCRIPTION,
    RS_NO_ATTRIBUTES_BLOCK,
    RS_NO_DOUBLE_BACKTICKS,
    RS_NONSTANDARD_DASH,
    RS_RAISE_DESCRIBED_IN_PROSE,
    RS_RAISES_SECTION_INCOMPLETE,
    RS_RETURN_DESCRIBED_IN_PROSE,
    RS_SUMMARY_COMMENT_AS_DOCSTRING,
    RS_TAG_COMMENT_CONTINUATION_INDENT,
    RS_TEMPORAL_MARKER,
    RS_TERMINAL_PUNCTUATION,
    RS_UNBACKTICKED_CODE_REFERENCE,
    RS_UNBACKTICKED_SIBLING_SYMBOL,
)
from repostyle.rules.comments import (
    check_acronym_casing_in_comments,
    check_banner_comment,
    check_comment_tag_format,
    check_comment_temporal_markers,
    check_comment_terminal_punctuation,
    check_disfavored_gcp_term_in_comments,
    check_nonstandard_dash_in_comments,
    check_tag_comment_continuation_indent,
)
from repostyle.rules.doc_fill import (
    check_doc_fill,
    check_doc_summary_overflow,
    check_double_space_after_period,
)
from repostyle.rules.doc_value import (
    check_arg_described_in_prose,
    check_doc_value_signal,
    check_field_described_in_class_docstring,
    check_raise_described_in_prose,
    check_raises_section_incomplete,
    check_return_described_in_prose,
)
from repostyle.rules.docstrings import (
    check_acronym_casing_in_docstrings,
    check_bullet_item_casing,
    check_bullet_item_casing_in_comments,
    check_disfavored_gcp_term_in_docstrings,
    check_docstring_section_alias,
    check_docstring_section_order,
    check_docstring_temporal_markers,
    check_docstring_terminal_punctuation,
    check_duplicate_docstring_section,
    check_field_comment_as_docstring,
    check_filler_docstring_opening,
    check_glued_code_span_in_comments,
    check_glued_code_span_in_docstrings,
    check_glued_code_span_in_md,
    check_inline_numbered_list,
    check_invalid_docstring_section,
    check_lowercase_entry_description,
    check_no_attributes_block,
    check_no_double_backticks_in_docstrings,
    check_no_double_backticks_in_md,
    check_nonstandard_dash_in_docstrings,
    check_summary_comment_as_docstring,
    check_unbackticked_code_reference,
    check_unbackticked_sibling_symbol,
    check_unbackticked_sibling_symbol_in_comments,
)

RULES = {
    RS_NO_ATTRIBUTES_BLOCK: (check_no_attributes_block,),
    RS_NO_DOUBLE_BACKTICKS: (
        check_no_double_backticks_in_md,
        check_no_double_backticks_in_docstrings,
    ),
    RS_DOC_FILL: (check_doc_fill,),
    RS_DOC_VALUE_SIGNAL: (check_doc_value_signal,),
    RS_SUMMARY_COMMENT_AS_DOCSTRING: (check_summary_comment_as_docstring,),
    RS_FIELD_COMMENT_AS_DOCSTRING: (check_field_comment_as_docstring,),
    RS_COMMENT_TAG_FORMAT: (check_comment_tag_format,),
    RS_TAG_COMMENT_CONTINUATION_INDENT: (check_tag_comment_continuation_indent,),
    RS_FILLER_DOCSTRING_OPENING: (check_filler_docstring_opening,),
    RS_TERMINAL_PUNCTUATION: (
        check_docstring_terminal_punctuation,
        check_comment_terminal_punctuation,
    ),
    RS_ARG_DESCRIBED_IN_PROSE: (check_arg_described_in_prose,),
    RS_FIELD_DESCRIBED_IN_CLASS_DOCSTRING: (check_field_described_in_class_docstring,),
    RS_RETURN_DESCRIBED_IN_PROSE: (check_return_described_in_prose,),
    RS_DOC_SUMMARY_OVERFLOW: (check_doc_summary_overflow,),
    RS_UNBACKTICKED_CODE_REFERENCE: (check_unbackticked_code_reference,),
    RS_GLUED_CODE_SPAN: (
        check_glued_code_span_in_md,
        check_glued_code_span_in_docstrings,
        check_glued_code_span_in_comments,
    ),
    RS_UNBACKTICKED_SIBLING_SYMBOL: (
        check_unbackticked_sibling_symbol,
        check_unbackticked_sibling_symbol_in_comments,
    ),
    RS_RAISE_DESCRIBED_IN_PROSE: (check_raise_described_in_prose,),
    RS_RAISES_SECTION_INCOMPLETE: (check_raises_section_incomplete,),
    RS_TEMPORAL_MARKER: (
        check_docstring_temporal_markers,
        check_comment_temporal_markers,
    ),
    RS_LOWERCASE_ENTRY_DESCRIPTION: (check_lowercase_entry_description,),
    RS_ACRONYM_CASING_IN_PROSE: (
        check_acronym_casing_in_docstrings,
        check_acronym_casing_in_comments,
    ),
    RS_DISFAVORED_GCP_TERM: (
        check_disfavored_gcp_term_in_docstrings,
        check_disfavored_gcp_term_in_comments,
    ),
    RS_BULLET_ITEM_CASING: (
        check_bullet_item_casing,
        check_bullet_item_casing_in_comments,
    ),
    RS_NONSTANDARD_DASH: (
        check_nonstandard_dash_in_docstrings,
        check_nonstandard_dash_in_comments,
    ),
    RS_BANNER_COMMENT: (check_banner_comment,),
    RS_INVALID_DOCSTRING_SECTION: (check_invalid_docstring_section,),
    RS_INLINE_NUMBERED_LIST: (check_inline_numbered_list,),
    RS_DOCSTRING_SECTION_ORDER: (check_docstring_section_order,),
    RS_DOCSTRING_SECTION_ALIAS: (check_docstring_section_alias,),
    RS_DUPLICATE_DOCSTRING_SECTION: (check_duplicate_docstring_section,),
    RS_DOUBLE_SPACE_AFTER_PERIOD: (check_double_space_after_period,),
}
