"""The `Violation` record, rule severities, and `RSnnn` id constants."""

from __future__ import annotations

import enum
from typing import NamedTuple


class Severity(enum.Enum):
    """How a rule's findings affect the exit status.

    An error-severity finding fails the run; a warning-severity finding is
    advisory and printed but does not fail it.
    """

    ERROR = "error"
    WARNING = "warning"


class Violation(NamedTuple):
    line: int
    """1-based line the violation points at."""
    col: int
    """1-based column the violation points at."""
    rule: str
    """The `RSnnn` id of the rule that produced it."""
    message: str
    """Human-readable description of what to fix."""


RS_ACRONYM_CASING = "RS001"
RS_TEST_NAMING = "RS002"
RS_NO_MOCK_PATCH = "RS003"
RS_NO_ATTRIBUTES_BLOCK = "RS004"
RS_NO_DOUBLE_BACKTICKS = "RS005"
RS_PORT_NO_IMPLEMENTATION = "RS006"
RS_DURATION_AS_TIMEDELTA = "RS007"
RS_NO_PHI_SAFE_EXC_INFO = "RS008"
RS_DOC_FILL = "RS009"
RS_BANNED_ABBREVIATION = "RS010"
RS_DISCOURAGED_CLASS_SUFFIX = "RS011"
RS_COGNITIVE_COMPLEXITY = "RS012"
RS_CONDITIONAL_TEST_LOGIC = "RS013"
RS_SLEEPY_TEST = "RS014"
RS_EXCESSIVE_MOCKING = "RS015"
RS_BEHAVIOR_VERIFICATION_ONLY = "RS016"
RS_BANNED_IMPORT_BY_PATH = "RS017"
RS_DOC_VALUE_SIGNAL = "RS018"
RS_ELEMENT_ORDER = "RS019"
RS_SUMMARY_COMMENT_AS_DOCSTRING = "RS020"
RS_FIELD_COMMENT_AS_DOCSTRING = "RS021"
RS_COMMENT_TAG_FORMAT = "RS022"
RS_FILLER_DOCSTRING_OPENING = "RS023"
RS_NO_NEGATED_BOOLEAN = "RS024"
RS_NO_MAKE_IN_PRODUCTION = "RS025"
RS_BOOLEAN_PREFIX_REQUIRED = "RS026"
RS_TOO_MANY_POSITIONAL_ARGS = "RS027"
RS_EXCEPTION_ALIAS = "RS028"
RS_SHOULD_BE_PRIVATE = "RS029"
RS_TERMINAL_PUNCTUATION = "RS030"
RS_ARG_DESCRIBED_IN_PROSE = "RS031"
RS_RETURN_DESCRIBED_IN_PROSE = "RS032"
RS_FILENAME_CONVENTION = "RS033"
RS_IMPERATIVE_DOCSTRING_OPENING = "RS034"
RS_DOC_SUMMARY_OVERFLOW = "RS035"
RS_UNBACKTICKED_CODE_REFERENCE = "RS036"
RS_GLUED_CODE_SPAN = "RS037"
RS_TAG_COMMENT_CONTINUATION_INDENT = "RS038"
RS_UNBACKTICKED_SIBLING_SYMBOL = "RS039"
RS_DEEPLY_NESTED_TYPE = "RS040"
RS_RAISE_DESCRIBED_IN_PROSE = "RS041"
RS_EQ_HASH_PAIRING = "RS042"
RS_RAISES_SECTION_INCOMPLETE = "RS043"
RS_PREDICATE_FUNCTION_NAMING = "RS044"
RS_TEMPORAL_MARKER = "RS045"
RS_RANGE_LEN_REINDEX = "RS046"
RS_LOWERCASE_ENTRY_DESCRIPTION = "RS047"
RS_PRIVATE_IMPORT = "RS048"
RS_ACRONYM_CASING_IN_PROSE = "RS049"
